BEGIN;

CREATE TABLE IF NOT EXISTS public.redemption_order_edits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT NOT NULL,
  period TEXT NOT NULL,
  old_request_id TEXT NOT NULL,
  new_request_id TEXT NOT NULL,
  old_items JSONB NOT NULL,
  new_items JSONB NOT NULL,
  old_points INTEGER NOT NULL,
  new_points INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.redemption_order_edits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.redemption_order_edits FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.edit_pending_redemption(
  p_uid TEXT,
  p_account_id TEXT,
  p_period TEXT,
  p_old_request_id TEXT,
  p_new_request_id TEXT,
  p_items JSONB,
  p_contact_info TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_point_balance INTEGER := 0;
  v_reserved_other INTEGER := 0;
  v_old_points INTEGER := 0;
  v_new_points INTEGER := 0;
  v_available_for_edit INTEGER := 0;
  v_old_items JSONB;
  v_item JSONB;
  v_order_count INTEGER := 0;
  v_existing_count INTEGER := 0;
  v_non_pending_count INTEGER := 0;
BEGIN
  IF p_uid IS NULL OR btrim(p_uid) = '' OR p_account_id !~ '^\d{19}$' THEN
    RAISE EXCEPTION 'valid creator credentials are required';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.kocs
    WHERE uid = p_uid AND account_id = p_account_id AND status = 'active'
  ) THEN
    RAISE EXCEPTION 'creator credentials do not match';
  END IF;
  IF p_period IS NULL OR btrim(p_period) = '' THEN
    RAISE EXCEPTION 'p_period is required';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.campaign_config
    WHERE period = p_period
      AND is_current_period = true
      AND redemption_open = true
      AND (redemption_close_at IS NULL OR NOW() < redemption_close_at)
  ) THEN
    RAISE EXCEPTION 'redemption window is closed';
  END IF;
  IF p_old_request_id IS NULL OR btrim(p_old_request_id) = '' THEN
    RAISE EXCEPTION 'the existing redemption request is required';
  END IF;
  IF p_new_request_id IS NULL OR btrim(p_new_request_id) = '' THEN
    p_new_request_id := gen_random_uuid()::TEXT;
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'p_items must be a non-empty array';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('redemption-edit|' || p_uid || '|' || p_period));

  PERFORM 1
  FROM public.redemption_orders
  WHERE uid = p_uid
    AND period = p_period
    AND request_id = p_old_request_id
    AND points_spent > 0
    AND status <> 'cancelled'
  FOR UPDATE;

  SELECT COUNT(*),
         COUNT(*) FILTER (WHERE status <> 'pending'),
         COALESCE(SUM(points_spent), 0)::INTEGER,
         COALESCE(jsonb_agg(jsonb_build_object(
           'id', id,
           'option_type', option_type,
           'option_name', option_name,
           'points_spent', points_spent,
           'reward_amount', reward_amount,
           'contact_info', contact_info,
           'status', status,
           'request_id', request_id
         ) ORDER BY id), '[]'::JSONB)
  INTO v_existing_count, v_non_pending_count, v_old_points, v_old_items
  FROM public.redemption_orders
  WHERE uid = p_uid
    AND period = p_period
    AND request_id = p_old_request_id
    AND points_spent > 0
    AND status <> 'cancelled';

  IF v_existing_count = 0 THEN
    RAISE EXCEPTION 'pending redemption request not found';
  END IF;
  IF v_non_pending_count > 0 THEN
    RAISE EXCEPTION 'only pending reward orders can be edited';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.redemption_orders
    WHERE uid = p_uid
      AND period = p_period
      AND points_spent > 0
      AND status <> 'cancelled'
      AND request_id IS DISTINCT FROM p_old_request_id
  ) THEN
    RAISE EXCEPTION 'multiple active redemption requests require admin review';
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    IF COALESCE(v_item->>'option_type', '') NOT IN ('diamonds', 'gplay', 'merch') THEN
      RAISE EXCEPTION 'unsupported reward type';
    END IF;
    IF COALESCE(NULLIF(v_item->>'option_name', ''), '') = '' THEN
      RAISE EXCEPTION 'option_name is required';
    END IF;
    IF COALESCE((v_item->>'points_spent')::INTEGER, 0) <= 0 THEN
      RAISE EXCEPTION 'points_spent must be positive';
    END IF;
    IF (v_item->>'option_type' = 'gplay' AND (v_item->>'points_spent')::INTEGER % 2 <> 0)
      OR (v_item->>'option_type' = 'merch' AND (v_item->>'points_spent')::INTEGER % 5 <> 0) THEN
      RAISE EXCEPTION 'reward points do not match the configured unit cost';
    END IF;
    v_new_points := v_new_points + (v_item->>'points_spent')::INTEGER;
  END LOOP;

  IF (
    SELECT COUNT(*) FROM jsonb_array_elements(p_items)
  ) <> (
    SELECT COUNT(DISTINCT item->>'option_type') FROM jsonb_array_elements(p_items) AS item
  ) THEN
    RAISE EXCEPTION 'duplicate reward types are not allowed';
  END IF;

  SELECT COALESCE(SUM(change), 0)::INTEGER
  INTO v_point_balance
  FROM public.point_logs
  WHERE uid = p_uid;

  SELECT COALESCE(SUM(points_spent), 0)::INTEGER
  INTO v_reserved_other
  FROM public.redemption_orders
  WHERE uid = p_uid
    AND status IN ('pending', 'processing')
    AND NOT (
      period = p_period
      AND request_id = p_old_request_id
      AND points_spent > 0
    );

  v_available_for_edit := v_point_balance - v_reserved_other;
  IF v_new_points > v_available_for_edit THEN
    RAISE EXCEPTION 'insufficient points: available %, required %', v_available_for_edit, v_new_points;
  END IF;

  INSERT INTO public.redemption_order_edits (
    uid, period, old_request_id, new_request_id,
    old_items, new_items, old_points, new_points
  ) VALUES (
    p_uid, p_period, p_old_request_id, p_new_request_id,
    v_old_items, p_items, v_old_points, v_new_points
  );

  DELETE FROM public.redemption_orders
  WHERE uid = p_uid
    AND period = p_period
    AND request_id = p_old_request_id
    AND points_spent > 0
    AND status = 'pending';

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.redemption_orders (
      uid, discord_name, koc_name, option_type, option_name, points_spent,
      reward_amount, contact_info, status, period, request_id, created_at
    ) VALUES (
      p_uid,
      COALESCE(v_item->>'discord_name', ''),
      COALESCE(v_item->>'koc_name', ''),
      v_item->>'option_type',
      v_item->>'option_name',
      (v_item->>'points_spent')::INTEGER,
      COALESCE(v_item->>'reward_amount', ''),
      COALESCE(NULLIF(v_item->>'contact_info', ''), p_contact_info),
      'pending', p_period, p_new_request_id, NOW()
    );
    v_order_count := v_order_count + 1;
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'order_count', v_order_count,
    'old_total', v_old_points,
    'new_total', v_new_points,
    'difference', v_new_points - v_old_points,
    'available_after', v_available_for_edit - v_new_points,
    'request_id', p_new_request_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.edit_pending_redemption(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.edit_pending_redemption(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT) TO anon, authenticated;

COMMIT;
