BEGIN;

CREATE TABLE IF NOT EXISTS public.platform_projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_key TEXT NOT NULL UNIQUE CHECK (project_key ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'archived')),
  default_locale TEXT NOT NULL DEFAULT 'en',
  default_timezone TEXT NOT NULL DEFAULT 'America/Los_Angeles',
  settings JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.platform_projects (
  project_key, name, default_locale, default_timezone, settings
) VALUES (
  'mlt-global',
  'My Leisure Time Global Creator Program',
  'en',
  'America/Los_Angeles',
  jsonb_build_object(
    'legacy_system', true,
    'creator_portal_language', 'en',
    'operating_region', 'global'
  )
)
ON CONFLICT (project_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.operational_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES public.platform_projects(id),
  period TEXT CHECK (period IS NULL OR period ~ '^\d{4}-\d{2}$'),
  workflow TEXT NOT NULL CHECK (workflow IN (
    'registration', 'submission', 'review', 'scoring', 'notification',
    'redemption', 'fulfillment', 'support', 'system'
  )),
  event_name TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('started', 'succeeded', 'failed', 'cancelled')),
  actor_type TEXT NOT NULL DEFAULT 'system' CHECK (actor_type IN ('creator', 'admin', 'system', 'agent')),
  subject_count INTEGER NOT NULL DEFAULT 0 CHECK (subject_count >= 0),
  duration_seconds INTEGER CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
  error_code TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_operational_events_project_period
  ON public.operational_events(project_id, period, workflow, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_operational_events_failures
  ON public.operational_events(project_id, created_at DESC)
  WHERE status = 'failed';

CREATE TABLE IF NOT EXISTS public.monthly_metric_snapshots_v2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES public.platform_projects(id),
  period TEXT NOT NULL CHECK (period ~ '^\d{4}-\d{2}$'),
  metric_key TEXT NOT NULL,
  metric_value NUMERIC NOT NULL,
  unit TEXT NOT NULL DEFAULT 'count',
  source TEXT NOT NULL,
  definition_version TEXT NOT NULL DEFAULT 'v1',
  notes TEXT NOT NULL DEFAULT '',
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(project_id, period, metric_key, definition_version)
);

CREATE INDEX IF NOT EXISTS idx_monthly_metric_snapshots_v2_period
  ON public.monthly_metric_snapshots_v2(project_id, period, metric_key);

ALTER TABLE public.platform_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_metric_snapshots_v2 ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.platform_projects FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.operational_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.monthly_metric_snapshots_v2 FROM PUBLIC, anon, authenticated;

COMMIT;
